-- -- 메뉴 테이블
-- DROP TABLE TBL_MENU CASCADE;
-- CREATE TABLE TBL_MENU
-- (
--     MENU_CD      VARCHAR(16)               NOT NULL,
--     MENU_CD_NAME VARCHAR(200),
--     UPPER_CD     VARCHAR(16) DEFAULT 'TOP' NOT NULL,
--     COST         NUMERIC (8,2),
--     CONSTRAINT PK_TBL_MENU PRIMARY KEY (MENU_CD)
-- );

-- 장바구니 시퀀스
DROP SEQUENCE SEQ_CART CASCADE;
CREATE SEQUENCE SEQ_CART
    START WITH 1
    INCREMENT BY 1;

-- 장바구니 테이블
DROP TABLE TBL_CART CASCADE;

CREATE TABLE TBL_CART
(
    CART_SEQ     INTEGER DEFAULT nextval('SEQ_CART') NOT NULL,
    ORDER_NUM    VARCHAR(50),
    MENU_CD      VARCHAR(16),
    MENU_CD_NAME VARCHAR(200),
    COST         NUMERIC(8, 2),
    CONSTRAINT PK_TBL_CART PRIMARY KEY (CART_SEQ, ORDER_NUM)
);
